const Shoes = [
  {
    id: 1,
    name: "Nike Air Max 90",
    brand: "Nike",
    manufactured: "2021",
    color: "White/Black/Grey",
    price: 100,
    gender: "Men",
    type: "Running",
    productType: "shoes",
    image:
      "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/wzitsrb4oucx9jukxsmc/air-max-90-mens-shoes-6n3vKB.png",
  },
  {
    id: 2,
    name: "Nike Air Zoom Pegasus 38",
    brand: "Nike",
    manufactured: "2021",
    color: "Pink/White",
    price: 120,
    gender: "Women",
    productType: "shoes",
    type: "Running",
    image:
      "https://product-images.21run.com/product/f/2/e/1/f2e145c6a85e798ffdfddf1e491e3fec588319b2_CW7358_601_PHSLH000_2000.jpeg?auto=compress&fill=solid&fill-color=ffffff&fit=fillmax&h=1250&w=1250&s=98d457035dbda8fb47ef3d0b8542d492",
  },
  {
    id: 3,
    name: "Adidas Ultraboost 21",
    brand: "Adidas",
    manufactured: "2021",
    color: "Black/White/Grey",
    price: 180,
    gender: "Men",
    productType: "shoes",
    type: "Running",
    image:
      "https://149367133.v2.pressablecdn.com/wp-content/uploads/2021/02/adidas-UltraBoost-21-gadgetmatch-20210225-01.jpg",
  },
  {
    id: 4,
    name: "Jordan Zoom 92",
    brand: "Jordan",
    manufactured: "2020",
    color: "Black/Red/White",
    price: 150,
    gender: "Men",
    productType: "shoes",
    type: "Basketball",
    image:
      "https://footwearnews.com/wp-content/uploads/2020/07/air-jordan-zoom-92.jpg?w=1024",
  },
  {
    id: 5,
    name: "New Balance Fresh Foam 1080v11",
    brand: "New Balance",
    manufactured: "2021",
    color: "Grey/Blue",
    price: 150,
    gender: "Men",
    productType: "shoes",
    type: "Running",
    image:
      "https://runningnw.com/wp-content/uploads/2020/12/New_Balance_1080v11_1.jpg",
  },
  {
    id: 6,
    name: "Adidas Ultraboost 21",
    brand: "Adidas",
    manufactured: "2021",
    color: "White/Silver",
    price: 180,
    gender: "Women",
    productType: "shoes",
    type: "Running",
    image:
      "https://cdn.shopify.com/s/files/1/0360/2130/5482/products/Ultraboost_21_Shoes_White_S23845_01_standard_1024x1024.jpg?v=1629002602",
  },
  {
    id: 7,
    name: "Under Armour HOVR Phantom2",
    brand: "Under Armour",
    manufactured: "2021",
    color: "Black/Grey",
    price: 140,
    gender: "Men",
    productType: "shoes",
    type: "Running",
    image:
      "https://cdn.listingmirror.com/3634/8106cc74-0084-588e-b6f7-ba56176c5253/full.jpg",
  },
  {
    id: 8,
    name: "ASICS GEL-Kayano 27",
    brand: "ASICS",
    manufactured: "2020",
    color: "Black",
    price: 160,
    gender: "Men",
    productType: "shoes",
    type: "Running",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTY3h4U7NVEcaU6d1Y2W-Cpf_fPpVeKsa1-3g&usqp=CAU",
  },
  {
    id: 9,
    name: "Reebok Nano X1",
    brand: "Reebok",
    manufactured: "2021",
    color: "Black/White",
    price: 130,
    gender: "Men",
    productType: "shoes",
    type: "Training",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeTlaJogWObBaHoY2Dobx3ufMKqjgDZAlcDg&usqp=CAU",
  },
  {
    id: 10,
    name: "Brooks Glycerin 19",
    brand: "Brooks",
    manufactured: "2021",
    color: "Black/White",
    price: 150,
    gender: "Men",
    productType: "shoes",
    type: "Running",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTRFa3oemeN-XHI5gqVw0fn-L0VEFbOfutbA&usqp=CAU",
  },
  {
    id: 11,
    name: "Mizuno Wave Rider 24",
    brand: "Mizuno",
    manufactured: "2020",
    color: "Blue/Green",
    price: 130,
    gender: "Men",
    productType: "shoes",
    type: "Running",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA7L_3qXF8n06sl1W5nme8i1URCCOqhOpLvQ&usqp=CAU",
  },
  {
    id: 12,
    name: "Puma Cell Surin 2 FM",
    brand: "Puma",
    manufactured: "2021",
    color: "Black/White",
    price: 70,
    gender: "Men",
    productType: "shoes",
    type: "Running",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSk1Zxld4HcVodl1WdYKzvM18v_0q9-x-z_w&usqp=CAU",
  },
  {
    id: 13,
    name: "Nike Air Max 270 React",
    brand: "Nike",
    manufactured: "2020-01-01",
    color: "Black/White",
    price: 120,
    gender: "Men's",
    productType: "shoes",
    type: "Running",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSECzLpu2t8dd8xME0DDZVRweZvUeZorMDelQ&usqp=CAU",
  },
  {
    id: 14,
    name: "Adidas Sprint 911",
    brand: "Adidas",
    manufactured: "2021-02-01",
    color: "Neon/White",
    price: 180,
    gender: "Men's",
    productType: "shoes",
    type: "Running",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSh8T7iYcXn3pWT8A7CFn4qWqfV-4al5crT_w&usqp=CAU",
  },
  {
    id: 15,
    name: "Reebok Classic Leather",
    brand: "Reebok",
    manufactured: "2021-03-01",
    color: "White/Gum",
    price: 75,
    gender: "Men's",
    productType: "shoes",
    type: "Casual",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCoxH2BpoRrjEr2gT-w8RHdRRcT0esk3vlcA&usqp=CAU",
  },
  {
    id: 14,
    name: "Air Jordan 4",
    brand: "Nike",
    manufactured: "2020",
    color: "White/Black",
    price: 190,
    gender: "Men",
    productType: "shoes",
    type: "Basketball Shoes",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMaua_UiCRKU3CUclqjI1qnDjqY8P5YTG4FQ&usqp=CAU",
  },
];

const Jeans = [
  {
    id: 1,
    name: "Levi's High Rise Skinny Jeans",
    brand: "Levi's",
    manufactured: "2013",
    color: "Blue",
    price: 69.5,
    gender: "Women",
    productType: "pants",
    type: "Skinny Jeans",
    image:
      "https://jeanstore.co.uk/cdn/shop/products/levi-s-womens-721-high-rise-skinny-jeans-good-afternoon-w25-l28-18882-042225xs-5400898992787-levi-s-jeans-29773909295298_740x.jpg?v=1628443162",
  },

  {
    id: 2,
    name: "Dickies 874 Work Pant",
    brand: "Dickies",
    manufactured: "1922",
    color: "Black",
    price: 22.99,
    gender: "Men",
    productType: "pants",
    type: "Work Pants",
    image:
      "https://i5.walmartimages.com/asr/c48c867f-3821-46bb-99cd-4b8c846651f0_1.58baf07a8301af48d035c583e50c8b29.jpeg",
  },
  {
    id: 3,
    name: "CK Straight Fit Jeans",
    brand: "Calvin Klein",
    manufactured: "1968",
    color: "Black",
    price: 69.5,
    gender: "Men",
    productType: "pants",
    type: "Straight Leg Jeans",
    image:
      "https://calvinklein.scene7.com/is/image/CalvinKlein/25027040_813_main?wid=720&hei=948&fmt=pjpeg&qlt=85%2C0&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0&iccEmbed=0",
  },
  {
    id: 4,
    name: "Levi's Men's Regular Fit Jeans",
    brand: "Levi's",
    manufactured: "1967",
    color: "Medium Stonewash",
    price: 59.5,
    gender: "Men",
    productType: "pants",
    type: "Regular Fit Jeans",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC-62vzlPc4QTrIuv5-KxCRWaYZZgHBHtWmA&usqp=CAU",
  },

  {
    id: 5,
    name: "Wrangler Straight Jeans",
    brand: "Wrangler",
    manufactured: "1947",
    color: "Dark Stonewash",
    price: 25.99,
    gender: "Men",
    productType: "pants",
    type: "Straight Leg Jeans",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvGNa5qdk2fsqKKYO7LlAD_0g4FgzCbdKjcw&usqp=CAU",
  },
  {
    id: 6,
    name: "Lucky Brand Straight Leg Jeans",
    brand: "Lucky Brand",
    manufactured: "1990",
    color: "Pacifica",
    price: 99.5,
    gender: "Men",
    productType: "pants",
    type: "Straight Leg Jeans",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXmJANYns0vwGM3Q-_sYDap2CNH1EhligmFA&usqp=CAU",
  },
  {
    id: 7,
    name: "Alkaram Straight Leg Jeans",
    brand: "Alkaram Studio",
    manufactured: "2020",
    color: "Blue",
    price: 100,
    gender: "Men",
    productType: "pants",
    type: "Straight Leg Jeans",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9XngWOzwcEGGQ6QuOFpvCV2_k-N7qkbKc_g&usqp=CAU",
  },
  {
    id: 8,
    name: "Men's Straight Leg Jeans",
    brand: "Nishat Linen",
    manufactured: "2020",
    color: "Blue",
    price: 28,
    gender: "Men",
    productType: "pants",
    type: "Straight Leg Jeans",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRc6QIXOqBQzqEpl0eVkcVdLnYUVVKa14kMAw&usqp=CAU",
  },
  {
    id: 9,
    name: "Gul Ahmed Straight Leg Jeans",
    brand: "Gul Ahmed",
    manufactured: "2020",
    color: "Blue",
    price: 60,
    gender: "Men",
    productType: "pants",
    type: "Straight Leg Jeans",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcNeW-baZtizrTr7EJ1UjIHvHWNWWiq3Raxw&usqp=CAU",
  },
  {
    id: 10,
    name: "Outfitters Straight Leg Jeans",
    brand: "Outfitters",
    manufactured: "2020",
    color: "Blue",
    price: 50,
    gender: "Men",
    productType: "pants",
    type: "Straight Leg Jeans",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShBIat-AJJNycxUCc0rzzQvWdx65Xq1_HjF1K-C7LyR75TWL99Wj-L1mn_uEen7Xu1TR4&usqp=CAU",
  },
];

const Watches = [
  {
    id: 1,
    name: "Rolex Submariner",
    brand: "Rolex",
    manufactured: "1953",
    color: "Black",
    price: 9000,
    gender: "Men",
    productType: "watches",
    type: "Dive Watch",
    image:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/new-rolex-submariner-ref-124060-gear-patrol-6-1598916014.jpg",
  },
  {
    id: 2,
    name: "Cartier Tank",
    brand: "Cartier",
    manufactured: "1917",
    color: "Gold",
    price: 5000,
    gender: "Women",
    productType: "watches",
    type: "Dress Watch",
    image:
      "https://www.cartier.com/variants/images/44733502651447063/img1/w960.jpg",
  },
  {
    id: 3,
    name: "Seiko 5",
    brand: "Seiko",
    manufactured: "1963",
    color: "Silver",
    price: 200,
    gender: "Men",
    productType: "watches",
    type: "Automatic Watch",
    image:
      "https://images.squarespace-cdn.com/content/v1/5c98539c29f2cc374150a758/fe3b55ef-585e-4146-81c6-5f333ae31529/1963_seiko_5_first_sportsmatic_1617533488_3c721acb.jpg",
  },
  {
    id: 4,
    name: "Omega Speedmaster",
    brand: "Omega",
    manufactured: "1957",
    color: "Silver",
    price: 5000,
    gender: "Men",
    productType: "watches",
    type: "Chronograph",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM5f6xf1iAeaDrcLqe_2udZQX7sclZoqZSjA&usqp=CAU",
  },
  {
    id: 5,
    name: "Tissot Le Locle",
    brand: "Tissot",
    manufactured: "1853",
    color: "Silver",
    price: 500,
    gender: "Men",
    productType: "watches",
    type: "Automatic Watch",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1eIrmp8OnH83oECIwe0q4ozcTSm3sZAd6fA&usqp=CAU",
  },
  {
    id: 6,
    name: "Casio G-Shock",
    brand: "Casio",
    manufactured: "1983",
    color: "Black",
    price: 150,
    gender: "Men",
    productType: "watches",
    type: "Sports Watch",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFETK2qrXwpTqwr1qmp26mdsMkpOEMAzAojQ&usqp=CAU",
  },
  {
    id: 7,
    name: "Movado Museum Classic",
    brand: "Movado",
    manufactured: "1947",
    color: "Silver",
    price: 800,
    gender: "Women",
    productType: "watches",
    type: "Dress Watch",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD336gffHbr4p0URDQi13UmqdkCWrLKKx_BA&usqp=CAU",
  },
  {
    id: 8,
    name: "Michael Kors Runway",
    brand: "Michael Kors",
    manufactured: "1981",
    color: "Rose Gold",
    price: 300,
    gender: "Women",
    productType: "watches",
    type: "Fashion Watch",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbBWbOCdTJr3OAwr47DX8Wfg0vY0KsvfipEg&usqp=CAU",
  },
  {
    id: 9,
    name: "Fossil Georgia",
    brand: "Fossil",
    manufactured: "1984",
    color: "Silver",
    price: 100,
    gender: "Women",
    productType: "watches",
    type: "Fashion Watch",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqOYszAz_LY0sKooj7XAk86DnzdrNiWswhNw&usqp=CAU",
  },
  {
    id: 10,
    name: "Tag Heuer Formula 1",
    brand: "Tag Heuer",
    manufactured: "1986",
    color: "Black",
    price: 1500,
    gender: "Women",
    productType: "watches",
    type: "Sports Watch",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgOXH6p24vwmzUNMxwm3ImIX-GsvqOYmmOKw&usqp=CAU",
  },
];

const Undergarments = [
  {
    id: 1,
    name: "CK Cotton Stretch Boxer Briefs",
    brand: "Calvin Klein",
    color: "Black",
    price: 25,
    manufactured: "2022",
    gender: "Men",
    productType: "undergarment",
    type: "Boxer Briefs",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGb__Ph7mzscPvgWmjLNICEnsBX5CwMnifWQ&usqp=CAU",
  },
  {
    id: 2,
    name: "Victoria's Secret Panties",
    brand: "Victoria's Secret",
    manufactured: "2022",
    color: "Pink",
    price: 12,
    gender: "Women",
    productType: "undergarment",
    type: "Hipster",
    image:
      "ht/tps://cdn.platform.next/COMMON/Items/Default/Default/ItemImages/AltItemShot/P74620.jpg",
  },
  {
    id: 3,
    name: "Tommy John Cotton Trunks",
    brand: "Tommy John",
    manufactured: "2022",
    color: "Navy",
    price: 30,
    gender: "Men",
    productType: "undergarment",
    type: "Trunks",
    image:
      "https://di2ponv0v5otw.cloudfront.net/posts/2023/01/01/63b1f61f5d686b9834b70327/m_63b1f6648d7a3c01ec2ab265.jpg",
  },
  {
    id: 4,
    name: "CK Carousel Bikini",
    brand: "Calvin Klein",
    manufactured: "2022",
    color: "Black",
    price: 20,
    gender: "Women",
    productType: "undergarment",
    type: "Bikini",
    image:
      "ht/tps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRVHlbP4wN_DDu9LK_uUGRc3Xu7EafvOCWbw&usqp=CAU",
  },
  {
    id: 5,
    name: "Signature Lace Thong",
    brand: "Hanky Panky",
    manufactured: "2022",
    color: "Red",
    price: 20,
    gender: "Women",
    productType: "undergarment",
    type: "Thong",
    image:
      "ht/tps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSioCZVSHjO1pNYiB8TpN6jEibPSfI8j8H2YA&usqp=CAU",
  },
  {
    id: 6,
    name: "Hanes Comfort Flex Fit Boxer",
    brand: "Hanes",
    manufactured: "2022",
    color: "Grey",
    price: 15,
    gender: "Men",
    productType: "undergarment",
    type: "Boxer Briefs",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTU8ZADseiyNjKHe7AuHbv78wr85l338e2krA&usqp=CAU",
  },
  {
    id: 7,
    name: "Adidas Climacool Boxer",
    brand: "Adidas",
    manufactured: "2022",
    color: "Grey",
    price: 25,
    gender: "Men",
    productType: "undergarment",
    type: "Boxer Briefs",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_1_sGCK1UEP2FF3gn6ib4YwWOVFsDYTZs2w&usqp=CAU",
  },
  {
    id: 8,
    name: "Under Armour Tech Boxerjock",
    brand: "Under Armour",
    manufactured: "2022",
    color: "Blue",
    price: 22,
    gender: "Men",
    productType: "undergarment",
    type: "Boxerjock",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPL2v6uUnIP1arD4XrJHuqQ2fvx-GDk3PuwA&usqp=CAU",
  },
  {
    id: 9,
    name: "Jockey Classic Briefs",
    brand: "Jockey",
    manufactured: "2022",
    color: "White",
    price: 15,
    gender: "Men",
    productType: "undergarment",
    type: "Briefs",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMqkOB9GttcbIpbVzBWzFi7CAtOePmklWUzQ&usqp=CAU",
  },
  {
    id: 10,
    name: "Victoria's Secret crochet",
    brand: "Victoria's Secret",
    manufactured: "2022",
    color: "Turquoise",
    price: 68,
    gender: "Women",
    productType: "undergarment",
    type: "Bikini",
    image:
      "ht/tps://media.nuuly.com/3aa60dcb-abc1-48d2-bae9-25cb8abbddd6.HEIC?$og-image$",
  },
  {
    id: 11,
    name: "Warner's Lace Hipster",
    brand: "Warner's",
    manufactured: "2022",
    color: "Black",
    price: 18,
    gender: "Women",
    productType: "undergarment",
    type: "Hipster",
    image:
      "ht/tps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFwkt8lSGlOdyXEid5iwVW2g1LO1oGPcYXdA&usqp=CAU",
  },
];
const Formalshirts = [
  {
    id: 1,
    name: "Ralph lauren Formal Shirt",
    type: "Formals",
    color: "White",
    size: "M",
    price: 180,
    manufactured: "2022",
    productType: "shirt",
    gender: "Women",
    image: "https://johnlewis.scene7.com/is/image/JohnLewis/005009185",
  },
  {
    id: 2,
    name: "Armani Formal Shirt",
    brand: "Armani",
    type: "Formals",
    size: "S",
    price: 200,
    gender: "Women",
    productType: "shirt",
    manufactured: "2022",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsVLK-YOkEftReDVsxXZ-hVeR6q0VSUmsiYQ&usqp=CAU",
  },
  {
    id: 3,
    name: "CK Formal Shirt",
    type: "Formals",
    color: "Blue",
    size: "L",
    price: 120,
    productType: "shirt",
    manufactured: "2022",
    gender: "Men",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIOyhRdIwWHwWSioqSHak8AAveadMMnB-OaA&usqp=CAU",
  },
  {
    id: 4,
    name: "Hugo Boss Formal Shirt",
    type: "Formals",
    color: "White",
    size: "M",
    price: 150,
    productType: "shirt",
    manufactured: "2022",
    gender: "Men",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4BJamIYsoA79i-YOBI9iCvA9ya3r8dV6n_w&usqp=CAU",
  },
  {
    id: 5,
    name: "Tommy Hilfiger Formal Shirt",
    type: "Formals",
    color: "Grey",
    size: "XL",
    price: 135,
    productType: "shirt",
    manufactured: "2022",
    gender: "Men",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxl0KqWmKjf3hn3Z8_MdCd6PGdt-xSlPbI5Q&usqp=CAU",
  },
  {
    id: 6,
    name: "Gucci Formal Shirt",
    type: "Formals",
    color: "Pink",
    size: "S",
    price: 250,
    productType: "shirt",
    manufactured: "2022",
    gender: "Women",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ55zH20osZLAQqa_NzcRDQf5IQyQ-pWZIHEQ&usqp=CAU",
  },
  {
    id: 7,
    name: "Zara Formal Shirt",
    type: "Formals",
    color: "White",
    size: "M",
    price: 90,
    productType: "shirt",
    manufactured: "2022",
    gender: "Men",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2LHzumreOBNilIpMwvWpCum4XgieWtGU32w&usqp=CAU",
  },
  {
    id: 8,
    name: "Channel Formal Shirt",
    type: "Formals",
    color: "Blue",
    size: "L",
    price: 280,
    productType: "shirt",
    manufactured: "2022",
    gender: "Women",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB88RMd0Z1xs2xqpmInxvFRzKgYkVvvCa3ig&usqp=CAU",
  },
  {
    id: 9,
    name: "Burberry Formal Shirt",
    type: "Formals",
    color: "Light Blue",
    size: "XL",
    price: 160,
    productType: "shirt",
    manufactured: "2022",
    gender: "Men",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTD0RoRP5hiJDgIQDCYLQUuvs5wrSXw0yfEA&usqp=CAU",
  },
  {
    id: 10,
    name: "Versace Formal Shirt",
    type: "Formals",
    color: "White",
    size: "S",
    price: 220,
    productType: "shirt",
    manufactured: "2022",
    gender: "Women",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqYdyVBqDkRKNl1SujA6IIK4L6o3i2XzC076X57YgeX4ze9klPEM6mU64qanIcq9VPeis&usqp=CAU",
  },
];
const Beauty = [
  {
    id: 1,
    name: "Olay Regenerist Micro-Sculpting Cream",
    brand: "Olay",
    category: "Moisturizer",
    skinType: "All",
    price: 25.99,
    gender: "Women",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfvA1SUnnprF_ZIIcp3E2o0ZQdqPYBH7LsGA&usqp=CAU",
  },
  {
    id: 2,
    name: "L'Oreal Paris True Match Liquid Foundation",
    brand: "L'Oreal",
    category: "Foundation",
    skinType: "All",
    price: 7.99,
    gender: "Women",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLzVG0ui3KzeCd0OUtAnF-scZrnqCsVSPCJQ&usqp=CAU",
  },
  {
    id: 3,
    name: "Maybelline New York Volum' Express Mascara",
    brand: "Maybelline",
    category: "Mascara",
    skinType: "All",
    price: 5.99,
    gender: "Women",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfUZbe-kbnSmiMVXiqmVObzZ-DtlYAQo0Flg&usqp=CAU",
  },
  {
    id: 4,
    name: "Neutrogena Hydro Boost Water Gel",
    brand: "Neutrogena",
    category: "Moisturizer",
    skinType: "All",
    price: 15.99,
    gender: "Women",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJAMHmhWszyaXEKzyHHWohB2KzfEbJrl1L_g&usqp=CAU",
  },
  {
    id: 5,
    name: "CeraVe Foaming Facial Cleanser",
    brand: "CeraVe",
    category: "Cleanser",
    skinType: "All",
    price: 14.99,
    gender: "Women",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROrcWkfoE32uSOTSpbQqeIOdoa9eEFPutNiA&usqp=CAU",
  },
  {
    id: 6,
    name: "The Ordinary Niacinamide 10% + Zinc 1%",
    brand: "The Ordinary",
    category: "Serum",
    skinType: "All",
    price: 5.9,
    gender: "Women",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTISPb8kGp0pLqmGYX3BvdQNZ1_8xiCuP6_Cw&usqp=CAU",
  },
  {
    id: 7,
    name: "Revlon ColorStay Lipstick",
    brand: "Revlon",
    category: "Lipstick",
    skinType: "All",
    price: 7.99,
    gender: "Women",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV4xJUsZ0_GQINaKZxya0CYO0_6D1DeJQFEA&usqp=CAU",
  },
  {
    id: 8,
    name: "Garnier SkinActive Micellar Cleansing Water",
    brand: "Garnier",
    category: "Cleanser",
    skinType: "All",
    price: 6.79,
    gender: "Women",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsRlpkKcxdcgMEGXvKMh8L01LxJrFSdhJhhA&usqp=CAU",
  },
  {
    id: 9,
    name: "Cetaphil Daily Facial Moisturizer SPF 15",
    brand: "Cetaphil",
    category: "Moisturizer",
    skinType: "All",
    price: 14.99,
    gender: "Women",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzvzKUiauUvrOjOMOqJO-qfqgpZaYyClhVgw&usqp=CAU",
  },
  {
    id: 10,
    name: "L'Oreal Paris Infallible Pro-Matte Liquid Lipstick",
    brand: "L'Oreal",
    category: "Lipstick",
    skinType: "All",
    price: 9.99,
    gender: "Women",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOqiSrGE-vb3I1v_n6pxYwmJtdiCbG2ceGtw&usqp=CAU",
  },
];
const Perfumes = [
  {
    id: 1,
    name: "Dolce & Gabbana Light Blue",
    brand: "Dolce & Gabbana",
    category: "Eau de Toilette",
    gender: "Women",
    price: 75.99,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNBRJ9LZ8pAbdu-xYMeswFhj4g0r3Y0dvmGA&usqp=CAU",
    type: "perfume",
  },
  {
    id: 2,
    name: "Chanel Coco Mademoiselle",
    brand: "Chanel",
    category: "Eau de Parfum",
    gender: "Women",
    price: 120.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRn3q-7xiyMaINEQ0gVgMxTNVOY5hd8FAFgaA&usqp=CAU",
    type: "perfume",
  },
  {
    id: 3,
    name: "Versace Bright Crystal",
    brand: "Versace",
    category: "Eau de Toilette",
    gender: "Women",
    price: 58.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWQYdQZkKIsTFVkMS2u-cb-BUd6iHZqu0lpw&usqp=CAU",
    type: "perfume",
  },
  {
    id: 4,
    name: "Gucci Bloom",
    brand: "Gucci",
    category: "Eau de Parfum",
    gender: "Women",
    price: 89.99,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_7ff8cqYtlQ6h8DN8Vi26B6oF2uablbfPPQ&usqp=CAU",
    type: "perfume",
  },
  {
    id: 5,
    name: "Armani Code",
    brand: "Giorgio Armani",
    category: "Eau de Toilette",
    gender: "Men",
    price: 68.5,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRV7_xevXflrCXOf87JNRFBIzFo5zaaLS0Lzg&usqp=CAU",
    type: "perfume",
  },
  {
    id: 6,
    name: "Dior Sauvage",
    brand: "Dior",
    category: "Eau de Toilette",
    gender: "Men",
    price: 95.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5dHQdzzS6jJjcWZZicFrOrEa7dmWR4zmO8g&usqp=CAU",
    type: "perfume",
  },
  {
    id: 7,
    name: "Paco Rabanne 1 Million",
    brand: "Paco Rabanne",
    category: "Eau de Toilette",
    gender: "Men",
    price: 79.99,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRykRkQId08C-TOfdTB7TK_OSrCZzmcprm6bw&usqp=CAU",
    type: "perfume",
  },
  {
    id: 8,
    name: "Yves Saint Laurent Black Opium",
    brand: "Yves Saint Laurent",
    category: "Eau de Parfum",
    gender: "Women",
    price: 115.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4hhAq6GPTFV8zqIzjWPX5vJhAGcBGMj6mmg&usqp=CAU",
    type: "perfume",
  },
  {
    id: 9,
    name: "Calvin Klein Euphoria",
    brand: "Calvin Klein",
    category: "Eau de Parfum",
    gender: "Women",
    price: 62.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5mdnnmI4nudmClrUNykN1BU4v04-qs_moBA&usqp=CAU",
    type: "perfume",
  },
  {
    id: 10,
    name: "Hugo Boss Bottled",
    brand: "Hugo Boss",
    category: "Eau de Toilette",
    gender: "Men",
    price: 74.5,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdxTeHqEfxjAYP5wGhAfnXiBhakfQwfhGYUg&usqp=CAU",
    type: "perfume",
  },
];
const Jewelry = [
  {
    id: 1,
    name: "Diamond Tennis Bracelet",
    brand: "Brilliance Jewelry",
    category: "Bracelet",
    gender: "Women",
    price: 2499.99,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_GnD9FoGD4W5RdWT3vWjMrwiFxMy2RcTe0g&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 2,
    name: "Sterling Silver Charm Bracelet",
    brand: "Pandora",
    category: "Bracelet",
    gender: "Women",
    price: 89.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIEx1cqb905Exlc7lnvSni_CKG5DI3zrlZ9w&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 3,
    name: "Gold Bangle Bracelet",
    brand: "Michael Kors",
    category: "Bracelet",
    gender: "Women",
    price: 175.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlnzPuuxEDjETM0lm0wnlbtQ8OBC50dYyQnw&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 4,
    name: "Silver Link Bracelet",
    brand: "Tiffany & Co.",
    category: "Bracelet",
    gender: "Women",
    price: 299.99,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVNKdGUNDhUt1R75a2UdhXA_cDBtgTUVyEpw&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 5,
    name: "Leather Cuff Bracelet",
    brand: "Fossil",
    category: "Bracelet",
    gender: "Women",
    price: 59.99,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZQumMO4f3-044c3Yr9xq917piUq3Ic1az5w&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 6,
    name: "Heart Locket Necklace",
    brand: "Alex and Ani",
    category: "Locket",
    gender: "Women",
    price: 69.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJv6sTLghaDqS0AELu0NzKO3A3E186KQNg3g&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 7,
    name: "Gold Plated Locket Pendant",
    brand: "Kate Spade",
    category: "Locket",
    gender: "Women",
    price: 99.99,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrRjeIR44sB1fFHC2UOq9rGoRT772GrPNZWA&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 8,
    name: "Diamond Locket Necklace",
    brand: "Blue Nile",
    category: "Locket",
    gender: "Women",
    price: 499.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfpfxMFjNND0a5tKRPWu4QUzZkv_FgTUByWQ&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 9,
    name: "Silver Heart Locket",
    brand: "James Avery",
    category: "Locket",
    gender: "Women",
    price: 159.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-GNGbU55ZqqwmfAvEB3Ri99_gP1t51WVdIQ&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 10,
    name: "Stainless Steel ID Bracelet",
    brand: "Engravable Jewelry",
    category: "Bracelet",
    gender: "Men",
    price: 49.99,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXH8IAkdWG6r28__wIK7JsxWVO_q5bOVprrA&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 11,
    name: "Silver Figaro Chain",
    brand: "Generic Brand",
    category: "Chain",
    gender: "Men",
    price: 39.99,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQFU4sIZSH9LNRghoRIflUjYZCN3gkpXZq8Q&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 12,
    name: "Gold Curb Chain",
    brand: "Luxury Jewelry",
    category: "Chain",
    gender: "Men",
    price: 299.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRz-EpWS2k2kRLqc1cYoZ2GFHrHJUVHA6ecpQ&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 13,
    name: "Stainless Steel Rope Chain",
    brand: "Fashion Chains",
    category: "Chain",
    gender: "Men",
    price: 49.99,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg0g9PfH-7SpO72QqgQ1rPBqWb8xQTV9hX7w&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 14,
    name: "Platinum Box Chain",
    brand: "Premium Chains",
    category: "Chain",
    gender: "Women",
    price: 599.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRc_hm0RRqEkEII0PyrW-dhvFVca0v6yyNOkw&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 15,
    name: "Rose Gold Wheat Chain",
    brand: "Designer Chains",
    category: "Chain",
    gender: "Women",
    price: 199.99,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1WrY332kaXdy4cD-XCTkdVks9P0DxaHO_5Q&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 16,
    name: "Sterling Silver Rolo Chain",
    brand: "Silver Chains",
    category: "Chain",
    gender: "Men",
    price: 79.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSbIQu2PCKq3kd_603DCDBvpuoPR1PGFWeOQ&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 17,
    name: "White Gold Snake Chain",
    brand: "Fine Jewelry",
    category: "Chain",
    gender: "Women",
    price: 499.99,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7lIKb5LRwML1c21p-oFnx6QrfIwgOqwfn2A&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 18,
    name: "Yellow Gold Herringbone Chain",
    brand: "High-End Chains",
    category: "Chain",
    gender: "Women",
    price: 899.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYpAFSdzWFmywsj2z-m9G6kCxSnpl_NL3ymQ&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 19,
    name: "Black Stainless Steel Franco Chain",
    brand: "Modern Chains",
    category: "Chain",
    gender: "Men",
    price: 69.99,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5iAum2tst30HkQB1SwB37oaI2yaK-yhLd6bDjtJEFCFgcEaRzzI2daguro7Ly9xnBaqY&usqp=CAU",
    type: "jewelry",
  },
  {
    id: 20,
    name: "Titanium Rolo Chain",
    brand: "Durable Chains",
    category: "Chain",
    gender: "Men",
    price: 129.0,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSht_p3Nr-d3o3f9Yql1ir-9HVXyd9I1r4tzA&usqp=CAU",
    type: "jewelry",
  },
];
const Furniture = [
  {
    id: 1,
    name: "Modern Sectional Sofa",
    brand: "Furniture Co.",
    category: "Sofa",
    price: 999.99,
    image: "#",
    type: "furniture",
  },
  {
    id: 2,
    name: "Wooden Dining Table",
    brand: "Home Furnishings",
    category: "Dining Table",
    price: 499.99,
    image: "#",
    type: "furniture",
  },
  {
    id: 3,
    name: "Leather Recliner Chair",
    brand: "Comfort Seating",
    category: "Chair",
    price: 799.99,
    image: "#",
    type: "furniture",
  },
  {
    id: 4,
    name: "Queen Size Bed Frame",
    brand: "Sleepwell",
    category: "Bed",
    price: 699.99,
    image: "#",
    type: "furniture",
  },
  {
    id: 5,
    name: "Modern Coffee Table",
    brand: "Living Space",
    category: "Coffee Table",
    price: 299.99,
    image: "#",
    type: "furniture",
  },
  {
    id: 6,
    name: "Bookshelf with Drawers",
    brand: "Organize It",
    category: "Bookshelf",
    price: 399.99,
    image: "#",
    type: "furniture",
  },
  {
    id: 7,
    name: "TV Stand with Storage",
    brand: "Entertainment Essentials",
    category: "TV Stand",
    price: 249.99,
    image: "#",
    type: "furniture",
  },
  {
    id: 8,
    name: "Writing Desk",
    brand: "Workspace Solutions",
    category: "Desk",
    price: 199.99,
    image: "#",
    type: "furniture",
  },
  {
    id: 9,
    name: "Accent Armchair",
    brand: "Style & Comfort",
    category: "Chair",
    price: 349.99,
    image: "#",
    type: "furniture",
  },
  {
    id: 10,
    name: "Storage Ottoman",
    brand: "Space Savers",
    category: "Ottoman",
    price: 149.99,
    image: "#",
    type: "furniture",
  },
];
const Health = [
  {
    id: 1,
    name: "Multivitamin Tablets",
    brand: "Nature's Best",
    category: "Supplements",
    price: 19.99,
    image: "#",
    type: "health",
  },
  {
    id: 2,
    name: "Protein Powder",
    brand: "Optimum Nutrition",
    category: "Supplements",
    price: 34.99,
    image: "#",
    type: "health",
  },
  {
    id: 3,
    name: "Fitness Tracker",
    brand: "Fitbit",
    category: "Wearable Devices",
    price: 129.99,
    image: "#",
    type: "health",
  },
  {
    id: 4,
    name: "Yoga Mat",
    brand: "Liforme",
    category: "Yoga Accessories",
    price: 79.99,
    image: "#",
    type: "health",
  },
  {
    id: 5,
    name: "Resistance Bands",
    brand: "INTEY",
    category: "Exercise Equipment",
    price: 24.99,
    image: "#",
    type: "health",
  },
  {
    id: 6,
    name: "Essential Oil Set",
    brand: "ArtNaturals",
    category: "Aromatherapy",
    price: 29.99,
    image: "#",
    type: "health",
  },
  {
    id: 7,
    name: "Cold Press Juicer",
    brand: "Breville",
    category: "Juicers",
    price: 199.99,
    image: "#",
    type: "health",
  },
  {
    id: 8,
    name: "Air Purifier",
    brand: "Dyson",
    category: "Air Quality",
    price: 399.99,
    image: "#",
    type: "health",
  },
  {
    id: 9,
    name: "Fitness Foam Roller",
    brand: "TriggerPoint",
    category: "Recovery Equipment",
    price: 39.99,
    image: "#",
    type: "health",
  },
  {
    id: 10,
    name: "Electric Toothbrush",
    brand: "Oral-B",
    category: "Oral Care",
    price: 79.99,
    image: "#",
    type: "health",
  },
];
export {
  Shoes,
  Jeans,
  Watches,
  Undergarments,
  Formalshirts,
  Beauty,
  Perfumes,
  Jewelry,
  Furniture,
  Health,
};
